include ../Makefile.inc

include makefile.inc

#required
CLASS =
SECTION =
LAB =

EXE = Submission

all : ${EXE}

clean : 
	${RM} ${EXE} *.o

showall :
	@ echo ${EXE}

${EXE} : ${TLPI_LIB}		# True as a rough approximation
